************* Module functions
dags/functions.py:16:70: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:53:0: C0301: Line too long (127/100) (line-too-long)
dags/functions.py:69:0: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:78:22: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:92:0: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:109:0: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:147:78: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:149:0: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:157:0: C0301: Line too long (120/100) (line-too-long)
dags/functions.py:179:57: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:180:170: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:180:0: C0301: Line too long (170/100) (line-too-long)
dags/functions.py:181:100: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:191:0: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:192:0: C0301: Line too long (151/100) (line-too-long)
dags/functions.py:195:0: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:206:83: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:208:0: C0303: Trailing whitespace (trailing-whitespace)
dags/functions.py:1:0: C0114: Missing module docstring (missing-module-docstring)
dags/functions.py:4:0: E0401: Unable to import 'pandas_gbq' (import-error)
dags/functions.py:6:0: E0611: No name 'bigquery' in module 'google.cloud' (no-name-in-module)
dags/functions.py:6:0: E0611: No name 'storage' in module 'google.cloud' (no-name-in-module)
dags/functions.py:67:4: W0622: Redefining built-in 'id' (redefined-builtin)
dags/functions.py:88:4: E1137: 'newsfeed2' does not support item assignment (unsupported-assignment-operation)
dags/functions.py:88:26: E1136: Value 'newsfeed2' is unsubscriptable (unsubscriptable-object)
dags/functions.py:94:4: E1137: 'newsfeed2' does not support item assignment (unsupported-assignment-operation)
dags/functions.py:94:43: E1136: Value 'newsfeed2' is unsubscriptable (unsubscriptable-object)
dags/functions.py:96:4: E1137: 'newsfeed2' does not support item assignment (unsupported-assignment-operation)
dags/functions.py:96:25: E1136: Value 'newsfeed2' is unsubscriptable (unsubscriptable-object)
dags/functions.py:97:4: E1137: 'newsfeed2' does not support item assignment (unsupported-assignment-operation)
dags/functions.py:97:24: E1136: Value 'newsfeed2' is unsubscriptable (unsubscriptable-object)
dags/functions.py:98:4: E1137: 'newsfeed2' does not support item assignment (unsupported-assignment-operation)
dags/functions.py:98:27: E1136: Value 'newsfeed2' is unsubscriptable (unsubscriptable-object)
dags/functions.py:99:4: E1137: 'newsfeed2' does not support item assignment (unsupported-assignment-operation)
dags/functions.py:99:26: E1136: Value 'newsfeed2' is unsubscriptable (unsubscriptable-object)
dags/functions.py:100:4: E1137: 'newsfeed2' does not support item assignment (unsupported-assignment-operation)
dags/functions.py:100:25: E1136: Value 'newsfeed2' is unsubscriptable (unsubscriptable-object)
dags/functions.py:154:10: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
dags/functions.py:213:10: C0209: Formatting a regular string which could be an f-string (consider-using-f-string)
dags/functions.py:185:0: W0613: Unused argument 'context' (unused-argument)
dags/functions.py:11:0: C0411: standard import "from datetime import datetime" should be placed before "import nltk" (wrong-import-order)

-----------------------------------
Your code has been rated at 0.68/10

